/*******************************************************************************
 * Copyright 2011 See AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
import org.gradle.internal.os.OperatingSystem

sourceSets {
	generator {
		java {
			srcDir 'generator'
		}
		resources {
			srcDir 'generator'
		}
	}
	main {
		java {
			srcDir 'src'
		}
		resources {
			srcDir 'res'
		}
	}
}
configurations {
	generatorCompile.extendsFrom testCompile
	generatorRuntime.extendsFrom testRuntime
}

configurations { generator }

dependencies {
	api libraries.robovm
	generatorImplementation 'com.github.javaparser:javaparser-core:3.24.2'
}

tasks.register('generate', JavaExec) {
	dependsOn configurations.generator

	mainClass = 'JavaCodeGenerator'
	classpath = sourceSets.generator.runtimeClasspath

	inputs.dir '../gdx-backend-robovm/src/'
	outputs.dir 'src/'
}

tasks.register('fetchMetalANGLEKit', Download) {
	doFirst {
		file("build/tmp").mkdirs();
	}
	src 'https://productionresultssa0.blob.core.windows.net/actions-results/b26bed91-36cb-4305-a540-35150d6e1181/workflow-job-run-036f7161-d983-5645-ad44-5f9ca43fc00f/artifacts/27d1ef936d3ae8dc20cf3b1c0962e713b82d32193cb476aa0bc1c5079e1631b9.zip?rscd=attachment%3B+filename%3D%22metalanglekit.zip%22&se=2025-06-23T06%3A15%3A29Z&sig=7TTCzRhraoJndDn01BhQUX78MCdFf6PewM9LVRKpI2w%3D&ske=2025-06-23T17%3A01%3A42Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-06-23T05%3A01%3A42Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-06-23T06%3A05%3A24Z&sv=2025-05-05'
//	src 'https://github.com/libgdx/MetalANGLEKit/releases/download/v1.2/metalanglekit.zip'
	dest 'build/tmp/MetalANGLEKit.zip'
	onlyIfModified true
	useETag "all"
}

tasks.register('verifyMetalANGLEKit', Verify) {
	dependsOn fetchMetalANGLEKit
	src 'build/tmp/MetalANGLEKit.zip'
	algorithm 'SHA-256'
	checksum 'c7785cbe15eb9e5962677513725c8f0e33039f344235cc7691ee5ac35ff5ea91'
}

tasks.register('extractMetalANGLEKit', Copy) {
	dependsOn verifyMetalANGLEKit

	doFirst {
		delete("res/META-INF/robovm/ios/libs/")
		delete("res/META-INF/robovm/ios/libs/")
		file("res/META-INF/robovm/ios/libs").mkdirs();
	}
	from zipTree('build/tmp/MetalANGLEKit.zip')
	into 'res/META-INF/robovm/ios/libs/'
}

tasks.register('jnigenBuildIOS') {
	dependsOn extractMetalANGLEKit
}

tasks.register('jnigenBuild') {
}

//Dummy task to make compatible with publish
tasks.register('jnigen') {
}

if(OperatingSystem.current() == OperatingSystem.MAC_OS) {
	jnigenBuild.dependsOn jnigenBuildIOS
}

processResources.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
sourcesJar.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
